# E:\proj_pyt\price_pars_service\price_pars_service\docker-compose.yml

services:
  # Основное приложение (WebSocket сборщик)
  app:
    build: .
    container_name: price_parser_service
    ports:
      - "8001:8000"  # ДРУГОЙ ПОРТ (не 8000)
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - DERIBIT_API_URL=${DERIBIT_API_URL:-https://test.deribit.com/api/v2}
      - DB_PATH=/app/data/prices.db
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - price_parser_network
    command: python -m app.websocket.start_websocket

  # Celery worker
  celery_worker:
    build: .
    container_name: price_parser_celery_worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DERIBIT_API_URL=${DERIBIT_API_URL:-https://test.deribit.com/api/v2}
      - DB_PATH=/app/data/prices.db
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - price_parser_network
    #на винде с другим не работает
    command: celery -A app.tasks.celery_app worker --loglevel=info -P threads

  # Celery beat (если нужен)
  celery_beat:
    build: .
    container_name: price_parser_celery_beat
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DERIBIT_API_URL=${DERIBIT_API_URL:-https://test.deribit.com/api/v2}
      - DB_PATH=/app/data/prices.db
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - price_parser_network
    command: celery -A app.tasks.celery_app beat --loglevel=info

  # Redis (свой экземпляр)
  redis:
    image: redis:alpine
    container_name: price_parser_redis
    ports:
      - "6380:6379"  # ДРУГОЙ ПОРТ (не 6379)
    volumes:
      - price_parser_redis_data:/data
    restart: unless-stopped
    networks:
      - price_parser_network

networks:
  price_parser_network:
    driver: bridge

volumes:
  price_parser_redis_data:
